### ISSUE TITLE
Authorization failed.... UPGRADE_MUSIC_MANAGER error

### ISSUE THREAD

**Issue by jugendhausldbg** [stevenewbs/gmpydl#23]
Hello, 
i really love your work for having a nice working musik-database downloading from google musik.
i wanted to sync my database after some months and now i have the following error:

```
Traceback (most recent call last):
  File "/home/markus/.local/lib/python3.8/site-packages/gmusicapi/protocol/shared.py", line 245, in perform
    cls.check_success(response, parsed_response)
  File "/home/markus/.local/lib/python3.8/site-packages/gmusicapi/protocol/musicmanager.py", line 92, in check_success
    raise CallFailure(
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 16: UPGRADE_MUSIC_MANAGER. See http://goo.gl/O6xe7 for more information. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/markus/.local/lib/python3.8/site-packages/gmusicapi/clients/musicmanager.py", line 131, in _perform_upauth
    self._make_call(musicmanager.AuthenticateUploader,
  File "/home/markus/.local/lib/python3.8/site-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/markus/.local/lib/python3.8/site-packages/gmusicapi/protocol/shared.py", line 259, in perform
    raise CallFailure(err_msg, e.callname) from e
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 16: UPGRADE_MUSIC_MANAGER. See http://goo.gl/O6xe7 for more information. 
(requests kwargs: {'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth', 'data': b'\n\x1170:85:C2:6F:F2:54\x12\x19jhburo (gmusicapi-13.0.0)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)', 'Authorization': '<omitted>'}})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 à](\x000\x80}8\x00H\x01P\x01X\x10`\x00j\x13\n\x1170:85:C2:6F:F2:54')
```

i made a fresh pip3-installation of gmusicapi but the error persists. any ideas?

**Comment by edoardoc** [comment]
having the same issue: I believe is due some changes in the backend, given that G is shutting down this service soon :/
have you found a way to download your music?

**Comment by stevenewbs** [comment]
I get the strong feeling that this is likely related to the service going away. Although that isn't based on any hard evidence.

**Comment by jugendhausldbg** [comment]
i wanted to have a look into the ytmusicapi, but i am at a point in my life i have no time to code or have a deeper look.
so sorry, found no way since the initial error. anyone else some luck?

**Comment by edoardoc** [comment]
There is this other project:

https://github.com/sigma67/ytmusicapi

It might be worth a shot to first transfer Google play music library to YouTube and then try and download it with that. I have no idea if this will be allowed though...

I have resorted to download my albums manually, I don't have many so it was manageable. Also I took the chance to drop some and reorganize the whole library... Now everything is going to VLC and it's going to be hard to convince me to trust Google with something so important as music.

Good luck to everyone
